version: "3.9"
services:
  django:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/valuation
      - DEBUG=true
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=valuation
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
