# Generated by Django 5.0.7 on 2025-10-25 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValuationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('vetted', 'Vetted')], default='free', max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('analyst_review', 'Analyst Review'), ('draft', 'Draft'), ('qa', 'QA'), ('finalized', 'Finalized')], default='new', max_length=32)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('standard', models.CharField(default='IVS 2024', max_length=64)),
                ('conclusion_value_low', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('conclusion_value_mid', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('conclusion_value_high', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuation.company')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('api', 'api'), ('manual', 'manual'), ('file', 'file')], max_length=16)),
                ('locator', models.TextField()),
                ('hash', models.CharField(blank=True, max_length=128)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuation.valuationcase')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=64)),
                ('metric', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('scenario', models.CharField(blank=True, max_length=64)),
                ('run_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuation.valuationcase')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=120)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuation.valuationcase')),
            ],
        ),
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.TextField()),
                ('source', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuation.valuationcase')),
            ],
        ),
    ]
