# Generated by Django 5.0.7 on 2025-10-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=64)),
                ('erp', models.FloatField(help_text='Equity risk premium (percentage points)')),
                ('default_spread', models.FloatField(blank=True, help_text='Default spread (percentage points)', null=True)),
                ('note', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('year', 'country')},
            },
        ),
    ]
