# Generated by Django 5.0.7 on 2025-10-25 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0002_countryrisk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('bond', 'bond'), ('option', 'option'), ('swap', 'swap')], max_length=16)),
                ('request_json', models.JSONField()),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(default=200)),
                ('x_user', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['instrument', 'created_at'], name='valuation_i_instrum_31b74e_idx')],
            },
        ),
    ]
